---
abstract: 'generate scaled or mangled images'
author:
  - 'Wolfgang Kinkeldei <wolfgang@kinkeldei.de>'
build_requires:
  Catalyst: 0
  Catalyst::Runtime: 0
  Catalyst::Test: 0
  FindBin: 0
  Image::Info: 0
  Path::Class::Dir: 0
  Path::Class::File: 0
  Test::Exception: 0
  Test::More: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Controller-Imager
requires:
  Catalyst::Controller: 0
  Catalyst::Runtime: 5.80
  FindBin: 1.47
  Image::Info: 1.31
  Imager: 0.86
  Imager::File::GIF: 0.82
  Imager::File::JPEG: 0.82
  Imager::File::PNG: 0.82
  MIME::Types: 0
  Moose: 1.0
  Moose::Util::TypeConstraints: 0
  Path::Class: 0.16
  strict: 0
version: 0.05
